// <auto-generated />
using System;
using LP2M_Revisi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LP2M_Revisi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Detailhakciptum", b =>
                {
                    b.Property<string>("Idhakcipta")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idhakcipta");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.HasKey("Idhakcipta", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailhakcipta", (string)null);
                });

            modelBuilder.Entity("Detailhakpaten", b =>
                {
                    b.Property<string>("Idhakpaten")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idhakpaten");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.HasKey("Idhakpaten", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailhakpaten", (string)null);
                });

            modelBuilder.Entity("Detailjurnal", b =>
                {
                    b.Property<string>("Idjurnal")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idjurnal");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.HasKey("Idjurnal", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailjurnal", (string)null);
                });

            modelBuilder.Entity("Detailpengabdian", b =>
                {
                    b.Property<string>("Idpengabdian")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengabdian");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.HasKey("Idpengabdian", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailpengabdian", (string)null);
                });

            modelBuilder.Entity("Detailprosiding", b =>
                {
                    b.Property<string>("IdPengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id_pengguna");

                    b.Property<string>("IdProsiding")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id_prosiding");

                    b.HasKey("IdPengguna", "IdProsiding");

                    b.HasIndex("IdProsiding");

                    b.ToTable("detailprosiding", (string)null);
                });

            modelBuilder.Entity("Detailseminar", b =>
                {
                    b.Property<string>("Idseminar")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idseminar");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.HasKey("Idseminar", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailseminar", (string)null);
                });

            modelBuilder.Entity("Detailsurattuga", b =>
                {
                    b.Property<string>("Idsurattugas")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idsurattugas");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.HasKey("Idsurattugas", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailsurattugas", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Buku", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("datetime")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("datetime")
                        .HasColumnName("inputdate");

                    b.Property<string>("Isbn")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("isbn");

                    b.Property<string>("Judulbuku")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judulbuku");

                    b.Property<string>("Penerbit")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("penerbit");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("Tahun")
                        .HasColumnType("int")
                        .HasColumnName("tahun");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("buku", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Detailbuku", b =>
                {
                    b.Property<string>("Idbuku")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idbuku");

                    b.Property<string>("Idpengguna")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("idpengguna");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Idbuku", "Idpengguna");

                    b.HasIndex("Idpengguna");

                    b.ToTable("detailbuku", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Hakciptum", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("date")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("date")
                        .HasColumnName("inputdate");

                    b.Property<string>("Judul")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judul");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Noaplikasi")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("noaplikasi");

                    b.Property<string>("Nosertifikat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nosertifikat");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("hakcipta", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Hakpaten", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("date")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("date")
                        .HasColumnName("inputdate");

                    b.Property<string>("Judul")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judul");

                    b.Property<string>("Nopermohonan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nopermohonan");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TanggalPenerimaan")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_penerimaan");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("hakpaten", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Jurnal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("datetime")
                        .HasColumnName("editdate");

                    b.Property<int?>("Halamanakhir")
                        .HasColumnType("int")
                        .HasColumnName("halamanakhir");

                    b.Property<int?>("Halamanawal")
                        .HasColumnType("int")
                        .HasColumnName("halamanawal");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("datetime")
                        .HasColumnName("inputdate");

                    b.Property<string>("Issn")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("issn");

                    b.Property<string>("Judulmakalah")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judulmakalah");

                    b.Property<string>("Kategori")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("kategori");

                    b.Property<string>("Namajurnal")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namajurnal");

                    b.Property<int?>("Nomor")
                        .HasColumnType("int")
                        .HasColumnName("nomor");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("url");

                    b.Property<int?>("Volume")
                        .HasColumnType("int")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("jurnal", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Pengabdianmasyarakat", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<byte[]>("Buktipendukung")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("buktipendukung");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("datetime")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("datetime")
                        .HasColumnName("inputdate");

                    b.Property<int?>("Jumlahpenerima")
                        .HasColumnType("int")
                        .HasColumnName("jumlahpenerima");

                    b.Property<byte[]>("Laporan")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("laporan");

                    b.Property<string>("MahasiswaProdiNim")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("mahasiswa_prodi_nim");

                    b.Property<string>("Namafilebukti")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namafilebukti");

                    b.Property<string>("Namafilelaporan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namafilelaporan");

                    b.Property<string>("Namafilesurat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namafilesurat");

                    b.Property<string>("Namakegiatan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namakegiatan");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<byte[]>("Surattugas")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("surattugas");

                    b.Property<DateTime?>("Waktupelaksanaan")
                        .HasColumnType("date")
                        .HasColumnName("waktupelaksanaan");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("pengabdianmasyarakat", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Pengguna", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("email");

                    b.Property<string>("Nama")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nama");

                    b.Property<string>("Notelepon")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("notelepon");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("password");

                    b.Property<int?>("Prodi")
                        .HasColumnType("int")
                        .HasColumnName("prodi");

                    b.Property<string>("Role")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Prodi");

                    b.ToTable("pengguna", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Prodi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nama");

                    b.HasKey("Id");

                    b.ToTable("prodi", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Prosiding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("date")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("date")
                        .HasColumnName("inputdate");

                    b.Property<string>("Judulpaper")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judulpaper");

                    b.Property<string>("Judulprogram")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judulprogram");

                    b.Property<string>("Kategori")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("kategori");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Penyelenggara")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("penyelenggara");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Tempatpelaksanaan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tempatpelaksanaan");

                    b.Property<DateTime?>("Waktuterbit")
                        .HasColumnType("date")
                        .HasColumnName("waktuterbit");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("prosiding", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Seminar", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("date")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("date")
                        .HasColumnName("inputdate");

                    b.Property<string>("Judulpaper")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judulpaper");

                    b.Property<string>("Judulprogram")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("judulprogram");

                    b.Property<string>("Kategori")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("kategori");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Penyelenggara")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("penyelenggara");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Tempatpelaksanaan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tempatpelaksanaan");

                    b.Property<DateTime?>("Waktupelaksanaan")
                        .HasColumnType("date")
                        .HasColumnName("waktupelaksanaan");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("seminar", (string)null);
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Surattuga", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("id");

                    b.Property<byte[]>("Buktipendukung")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("buktipendukung");

                    b.Property<string>("Editby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("editby");

                    b.Property<DateTime?>("Editdate")
                        .HasColumnType("datetime")
                        .HasColumnName("editdate");

                    b.Property<string>("Inputby")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("inputby");

                    b.Property<DateTime?>("Inputdate")
                        .HasColumnType("datetime")
                        .HasColumnName("inputdate");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Masapelaksanaan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("masapelaksanaan");

                    b.Property<string>("Namafile")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namafile");

                    b.Property<string>("Namafilesurat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namafilesurat");

                    b.Property<string>("Namakegiatan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("namakegiatan");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<byte[]>("Surattugas")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("surattugas");

                    b.Property<DateTime?>("tanggalselesai")
                        .HasColumnType("datetime")
                        .HasColumnName("tanggalselesai");

                    b.HasKey("Id");

                    b.HasIndex("Editby");

                    b.HasIndex("Inputby");

                    b.ToTable("surattugas", (string)null);
                });

            modelBuilder.Entity("Detailhakciptum", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Hakciptum", null)
                        .WithMany()
                        .HasForeignKey("Idhakcipta")
                        .IsRequired()
                        .HasConstraintName("FK_detailhakcipta_hakcipta");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailhakcipta_pengguna");
                });

            modelBuilder.Entity("Detailhakpaten", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Hakpaten", null)
                        .WithMany()
                        .HasForeignKey("Idhakpaten")
                        .IsRequired()
                        .HasConstraintName("FK_detailhakpaten_hakpaten");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailhakpaten_pengguna");
                });

            modelBuilder.Entity("Detailjurnal", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Jurnal", null)
                        .WithMany()
                        .HasForeignKey("Idjurnal")
                        .IsRequired()
                        .HasConstraintName("FK_detailjurnal_jurnal");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailjurnal_pengguna");
                });

            modelBuilder.Entity("Detailpengabdian", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengabdianmasyarakat", null)
                        .WithMany()
                        .HasForeignKey("Idpengabdian")
                        .IsRequired()
                        .HasConstraintName("FK_detailpengabdian_pengabdianmasyarakat");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailpengabdian_pengguna");
                });

            modelBuilder.Entity("Detailprosiding", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("IdPengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailprosiding_pengguna");

                    b.HasOne("LP2M_Revisi.Models.Prosiding", null)
                        .WithMany()
                        .HasForeignKey("IdProsiding")
                        .IsRequired()
                        .HasConstraintName("FK_detailprosiding_prosiding");
                });

            modelBuilder.Entity("Detailseminar", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailseminar_pengguna");

                    b.HasOne("LP2M_Revisi.Models.Seminar", null)
                        .WithMany()
                        .HasForeignKey("Idseminar")
                        .IsRequired()
                        .HasConstraintName("FK_detailseminar_seminar");
                });

            modelBuilder.Entity("Detailsurattuga", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", null)
                        .WithMany()
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailsurattugas_pengguna");

                    b.HasOne("LP2M_Revisi.Models.Surattuga", null)
                        .WithMany()
                        .HasForeignKey("Idsurattugas")
                        .IsRequired()
                        .HasConstraintName("FK_detailsurattugas_surattugas");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Buku", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("BukuEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_bukus_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("BukuInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_bukus_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Detailbuku", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Buku", "IdbukuNavigation")
                        .WithMany("Detailbukus")
                        .HasForeignKey("Idbuku")
                        .IsRequired()
                        .HasConstraintName("FK_detailbuku_buku");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "IdpenggunaNavigation")
                        .WithMany("Detailbukus")
                        .HasForeignKey("Idpengguna")
                        .IsRequired()
                        .HasConstraintName("FK_detailbuku_pengguna");

                    b.Navigation("IdbukuNavigation");

                    b.Navigation("IdpenggunaNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Hakciptum", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("HakciptumEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_hakciptas_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("HakciptumInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_hakciptas_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Hakpaten", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("HakpatenEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_hakpatens_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("HakpatenInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_hakpatens_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Jurnal", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("JurnalEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_jurnals_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("JurnalInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_jurnals_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Pengabdianmasyarakat", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("PengabdianmasyarakatEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_pengabdianmasyarakats_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("PengabdianmasyarakatInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_pengabdianmasyarakats_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Pengguna", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Prodi", "ProdiNavigation")
                        .WithMany("Penggunas")
                        .HasForeignKey("Prodi")
                        .HasConstraintName("FK_pengguna_prodi");

                    b.Navigation("ProdiNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Prosiding", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("ProsidingEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_prosidings_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("ProsidingInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_prosidings_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Seminar", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("SeminarEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_seminars_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("SeminarInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_seminars_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Surattuga", b =>
                {
                    b.HasOne("LP2M_Revisi.Models.Pengguna", "EditbyNavigation")
                        .WithMany("SurattugaEditbyNavigations")
                        .HasForeignKey("Editby")
                        .HasConstraintName("FK_surattugas_s2");

                    b.HasOne("LP2M_Revisi.Models.Pengguna", "InputbyNavigation")
                        .WithMany("SurattugaInputbyNavigations")
                        .HasForeignKey("Inputby")
                        .HasConstraintName("FK_surattugas_s");

                    b.Navigation("EditbyNavigation");

                    b.Navigation("InputbyNavigation");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Buku", b =>
                {
                    b.Navigation("Detailbukus");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Pengguna", b =>
                {
                    b.Navigation("BukuEditbyNavigations");

                    b.Navigation("BukuInputbyNavigations");

                    b.Navigation("Detailbukus");

                    b.Navigation("HakciptumEditbyNavigations");

                    b.Navigation("HakciptumInputbyNavigations");

                    b.Navigation("HakpatenEditbyNavigations");

                    b.Navigation("HakpatenInputbyNavigations");

                    b.Navigation("JurnalEditbyNavigations");

                    b.Navigation("JurnalInputbyNavigations");

                    b.Navigation("PengabdianmasyarakatEditbyNavigations");

                    b.Navigation("PengabdianmasyarakatInputbyNavigations");

                    b.Navigation("ProsidingEditbyNavigations");

                    b.Navigation("ProsidingInputbyNavigations");

                    b.Navigation("SeminarEditbyNavigations");

                    b.Navigation("SeminarInputbyNavigations");

                    b.Navigation("SurattugaEditbyNavigations");

                    b.Navigation("SurattugaInputbyNavigations");
                });

            modelBuilder.Entity("LP2M_Revisi.Models.Prodi", b =>
                {
                    b.Navigation("Penggunas");
                });
#pragma warning restore 612, 618
        }
    }
}
